name: login
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  url_launcher: ^5.0.2
  mongo_dart: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo1.png
    - assets/alucard.jpg
  fonts:
      - family: Nunito
        fonts:
          - asset: assets/Nunito.ttf